# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David Yoo
email: your-email@domain.com
description: >
  David Yoo is a designer and developer based in San Francisco, CA.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidkyoo.com"
twitter_username: _davidyoo
github_username:  yookd
linkedin_username: yookd
sass:
  sass_dir: _sass
assets:
  prefix: "/assets"
  sources:
    - assets/fonts
    - assets/css

# Build settings
markdown: kramdown
